export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_MAPSTYLE = 'SET_MAPSTYLE';

export const TOGGLE_DATA_LOADED = 'TOGGLE_DATA_LOADED';
export const TOGGLE_MAP_LOADED = 'TOGGLE_MAP_LOADED';
export const TOGGLE_LOCATION_HOVER = 'TOGGLE_LOCATION_HOVER';

export const SET_CENTER = 'SET_CENTER';
export const SET_EXCERPT_ID = 'SET_EXCERPT_ID';
