export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_MAPSTYLE = 'SET_MAPSTYLE';

export const TOGGLE_DATA_LOADED = 'TOGGLE_DATA_LOADED';
export const TOGGLE_MAP_LOADED = 'TOGGLE_MAP_LOADED';
export const TOGGLE_LOCATION_HOVER = 'TOGGLE_LOCATION_HOVER';
export const TOGGLE_PANTOMARKER = 'TOGGLE_PANTOMARKER';

export const SET_CENTER = 'SET_CENTER';
export const SET_HOVERED_LOCATION_ID = 'SET_HOVERED_LOCATION_ID';
export const SET_ACTIVE_LOCATION_ID = 'SET_ACTIVE_LOCATION_ID';
export const SET_TRIP_BOUNDS = 'SET_TRIP_BOUNDS';
export const SET_ZOOM = 'SET_ZOOM';
