export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_MAPSTYLE = 'SET_MAPSTYLE';

export const TOGGLE_DATA_LOADED = 'TOGGLE_DATA_LOADED';
export const TOGGLE_MAP_LOADED = 'TOGGLE_MAP_LOADED';
export const TOGGLE_LOCATION_HOVER = 'TOGGLE_LOCATION_HOVER';
export const TOGGLE_PANTOMARKER = 'TOGGLE_PANTOMARKER';
export const TOGGLE_ACTIVE_ARTICLE = 'TOGGLE_ACTIVE_ARTICLE';

export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_ZOOM = 'SET_ZOOM';
export const SET_TRIP_BOUNDS = 'SET_TRIP_BOUNDS';

export const SET_ACTIVE_ARTICLE_ID = 'SET_ACTIVE_ARTICLE_ID';
export const SET_HOVERED_LOCATION_ID = 'SET_HOVERED_LOCATION_ID';
export const SET_ACTIVE_LOCATION_ID = 'SET_ACTIVE_LOCATION_ID';
export const SHOW_ARTICLE = 'SHOW_ARTICLE';
